[package]
name = "counter_contract"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = "20.1.0"  # Use latest version from https://crates.io/crates/soroban-sdk

[lib]
crate-type = ["cdylib", "lib"]
